import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#00504c',
        'secondary-fixed': '#ffdbcc',
        'outline': '#6d7a78',
        'on-secondary': '#ffffff',
        'surface-tint': '#006a65',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#2a313d',
        'primary-fixed': '#87f5ec',
        'on-background': '#151c27',
        'inverse-on-surface': '#ebf1ff',
        'surface-variant': '#dce2f3',
        'surface-container-highest': '#dce2f3',
        'on-tertiary-fixed': '#360f00',
        'primary-fixed-dim': '#69d8d0',
        'on-error-container': '#93000a',
        'tertiary': '#914724',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb597',
        'on-tertiary-container': '#fffbff',
        'surface-container-high': '#e2e8f8',
        'surface-container-low': '#f0f3ff',
        'on-surface-variant': '#3d4948',
        'surface-container': '#e7eefe',
        'secondary': '#F86501',
        'on-primary-fixed': '#00201e',
        'on-primary': '#ffffff',
        'on-secondary-container': '#581f00',
        'inverse-primary': '#69d8d0',
        'on-tertiary-fixed-variant': '#763311',
        'on-primary-container': '#f3fffd',
        'secondary-fixed-dim': '#ffb695',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#351000',
        'secondary-container': '#ff6a0b',
        'primary': '#00938C',
        'on-surface': '#151c27',
        'error': '#ba1a1a',
        'primary-container': '#00837c',
        'on-secondary-fixed-variant': '#7b2e00',
        'tertiary-container': '#b05f3a',
        'background': '#f9f9ff',
        'surface-dim': '#d3daea',
        'outline-variant': '#bcc9c7',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface': '#f9f9ff',
        'surface-bright': '#f9f9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '4px',
        md: '16px',
        xl: '32px',
        gutter: '24px',
        margin: '40px',
        base: '4px',
        sm: '8px',
        lg: '24px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'stat-value': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'h3': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'stat-value': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}

export default config
